In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
print(torch.__version__)

2.8.0+cu126


In [ ]:
vector=torch.tensor([7,6])
vector


tensor([7, 6])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
matrix = torch.tensor([[1, 2], [3, 4]])
matrix[0]

tensor([1, 2])

In [ ]:
matrix = torch.tensor([[1, 2], [3, 4]])

In [ ]:
tensor=torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([1, 3, 3])

RANDOM Tensors

In [ ]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.6023, 0.2148, 0.7571, 0.3635],
        [0.2541, 0.8496, 0.0916, 0.9937],
        [0.9409, 0.2655, 0.2590, 0.4795]])

In [ ]:
torch.rand(3,3)

tensor([[0.4564, 0.8223, 0.5419],
        [0.4182, 0.8234, 0.5323],
        [0.2120, 0.4844, 0.6735]])

In [ ]:
zeros=torch.zeros(size=(3,4))

In [ ]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros=torch.ones(size=(3,4))


In [ ]:
zeros

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
zeros.dtype

torch.float32

In [ ]:
torch.range(0,10)

/tmp/ipython-input-497691777.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
one_to_ten=torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#Manipulating Tensors
#Addition
#Subtraction
#multplication(element wise)
#MATRIX multplicaton

In [ ]:
tensor=torch.tensor([1,2,3,])
tensor+10

tensor([11, 12, 13])

In [ ]:
tensor*10

tensor([10, 20, 30])

In [ ]:
tensor-10

tensor([-9, -8, -7])

In [ ]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor,10)

tensor([11, 12, 13])

MATRIX multplicaton
#inner dismensions must match
#(3,2)@(



In [ ]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.2343, 0.6602, 0.3359],
        [0.2289, 0.3709, 0.5531],
        [0.3243, 0.4228, 0.8679]])

In [ ]:
torch.matmul(torch.rand(2,3),torch.rand(3,2))

tensor([[0.8414, 0.6940],
        [1.6889, 1.6139]])

In [ ]:
torch.tensor([0,10,20,30,40,50,60,70,80,90])

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
my_tensor = torch.tensor([0,10,20,30,40,50,60,70,80,90])
torch.min(my_tensor)

tensor(0)

In [ ]:
# Find the minimum value and its index of the tensor
min_value, min_index = torch.min(my_tensor, dim=0)
print(f"Minimum value: {min_value}")
print(f"Index of minimum value: {min_index}")

Minimum value: 0
Index of minimum value: 0


In [ ]:
torch.max(my_tensor)

tensor(90)

In [ ]:
# Find the maximum value and its index of the tensor
max_value, max_index = torch.max(my_tensor, dim=0)
print(f"Maximum value: {max_value}")
print(f"Index of maximum value: {max_index}")

Maximum value: 90
Index of maximum value: 9


In [ ]:
torch.tensor(45.)

tensor(45.)

In [ ]:
torch.argmin(my_tensor)

tensor(0)

In [ ]:
torch.argmax(my_tensor)

tensor(9)

In [ ]:
torch.tensor(90)

tensor(90)

In [ ]:
torch.tensor(90)

tensor(90)

In [ ]:
import torch

In [ ]:
x = torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
z = x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# changing z changes x
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# torch.square()-removes all single dimensions from a target tensor
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])